### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException in parse()

### ISSUE THREAD

**Issue by timgilbert** [jstrachan/scopt#1]
I get the above error running the following scala code with the single argument "-v":

```
import org.github.scopt._

object test {

  def main(argv: Array[String]) {

    var verbose = false
    val parser = new OptionParser("scopt") {
      booleanOpt("v", "verbose", "If true, be verbose", {v: Boolean => verbose = v})
    }

    if (!parser.parse(argv)) {
      println("parser returned false")
    }

    println(if (verbose) "true" else "false")
  }
}
```

The full traceback is:

```
java.lang.ArrayIndexOutOfBoundsException: 1
        at scala.collection.mutable.WrappedArray$ofRef.apply(WrappedArray.scala:99)
        at org.github.scopt.OptionParser.parse(Options.scala:437)
        at test$.main(test.scala:12)
        at test.main(test.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at sbt.Run.run0(Run.scala:60)
        at sbt.Run.execute$1(Run.scala:47)
        at sbt.Run$$anonfun$run$2.apply(Run.scala:50)
        at sbt.Run$$anonfun$run$2.apply(Run.scala:50)
        at sbt.TrapExit$.executeMain$1(TrapExit.scala:33)
        at sbt.TrapExit$$anon$1.run(TrapExit.scala:42)
```

I'm running off the current master branch (compiled into my local ivy repo).

**Comment by eed3si9n** [comment]
I don't know if `ArrayIndexOutOfBoundsException` is the right response here, but if you just want to pass "-v", it should be written as:

```
val parser = new OptionParser("scopt") {
  opt("v", "verbose", "If true, be verbose", { verbose = true })
}
```

**Comment by eed3si9n** [comment]
I made the change so it displays helpful error message:
    Error: missing value after '-v'

instead of blowing up.

http://github.com/jstrachan/scopt/commit/cc1450e3678b7251cbb05882faf41db0cdab7aa2
